environment:
  PAKET.VERSION: "3.1.7.0"
  matrix:
    # node.js
    - nodejs_version: "6"

# Build on both platforms
platform:
  - x64

shallow_clone: true

# Install scripts. (runs after repo cloning)
install:
  # Get the latest version of $env:nodejs_version
  - ps: Install-Product node $env:nodejs_version  
  - ps: node --version
  - ps: npm install -g npm
  - ps: npm --version

build_script:
  - build.cmd clienttests

test: off
